### ISSUE TITLE
MacOS and Iphone doesn't show Lucida Sans

### ISSUE THREAD

**Issue by GlaceCoding** [Tripouille/valheim-skali#37]
https://stackoverflow.com/questions/13763109/iphone-wont-show-lucida-sans?lq=1

On mac we don't have Lucida Sans font, you should set a replacement font. By example: `font-family: "Lucida Sans", SANS-SERIF;`

**Comment by GlaceCoding** [comment]
![Screen Shot 2022-02-01 at 6 30 11 PM](https://user-images.githubusercontent.com/92152391/152019587-9efd4f79-1189-4fc4-b9c4-d057e8d7dec6.png)

**Comment by Chinimala** [comment]
Hello,
Thank you for reporting, it should be fixed on branch "refactor/style" (on commit https://github.com/Tripouille/valheim-skali/pull/39/commits/aaed282883b845548b4d23fd6c1bc14f54986041), and it can be tested on this link : https://skali-git-refactor-style-tripouille.vercel.app.
I also applied your advice from your last PR about preloading the Norse font :)

**Comment by GlaceCoding** [comment]
[off-topic]
@Chinimala Votre serveur est public ? [il me semble que oui (si c'est bien lui)](https://top-serveurs.net/valheim/valhabba-valheim) Aucune information sur comment le rejoindre sur le site je serais curieux d'y jouer.

**Comment by Chinimala** [comment]
> [off-topic] @Chinimala Votre serveur est public ? [il me semble que oui (si c'est bien lui)](https://top-serveurs.net/valheim/valhabba-valheim) Aucune information sur comment le rejoindre sur le site je serais curieux d'y jouer.

Oui c'est bien lui et il est public, tu as toutes les infos sur le discord ;) Pour le rejoindre, il faut lire le règlement, faire une candidature et passer un (parfois long) rendez-vous avec les modos.
Effectivement le site n'en est encore à ses débuts (et est d'ailleurs inconnu de ses membres, alors n'en dis rien si tu vas sur le serveur Valheim s'il te plaît), mais plus tard j'aimerais y mettre le système de candidature et de prise de rendez-vous de whitelist du serveur effectivement

**Comment by GlaceCoding** [comment]
Tu fais bien de me le dire, bouche cousue! 🤫
